Add rustfmt check to CI and run_all_checks
This also bumps our minimum rustc to 1.29, which was the version I'd
been running rustfmt with.

diff --git a/rust/run_all_checks b/rust/run_all_checks
--- a/rust/run_all_checks
+++ b/rust/run_all_checks
@@ -8,6 +8,14 @@ if ! (RUSTFLAGS="-D warnings" cargo check --all); then
 fi
 
 printf 'Check passed!\n'
+
+printf 'Running rustfmt:\n'
+
+if ! (cargo fmt --all -- --check); then
+    printf '\nRustfmt failed. Please run rustfmt.\n'
+    exit $?
+fi
+
 printf 'Running "cargo test --all"\n'
 
 if ! (cargo test --all); then
